"""initial tables

Revision ID: 030b1ac1fb7b
Revises: 
Create Date: 2025-05-18 15:23:46.639656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030b1ac1fb7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coa_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['coai_dto_group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_coa_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coa_access_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coa_access_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_coa_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_coa_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_coa_access_group_id'))

    op.drop_table('user_coa_access')
    # ### end Alembic commands ###
